In [2]:
print("Versão do Python:")
!python --version

Versão do Python:
Python 3.14.4

## Libraries

In [3]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn
!pip install xgboost

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.4.4)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: matplotlib in ./.venv/lib/python3.14/site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.14/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: seaborn in ./.venv/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./.venv/lib/python3.14/site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in ./.venv/lib/python3.14/site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in ./.venv/lib/python3.14/site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./.venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: xgboost in ./.venv/lib/python3.14/site-packages (3.2.0)
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (from xgboost) (2.4.4)
Requirement already satisfied: nvidia-nccl-cu12 in ./.venv/lib/python3.14/site-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in ./.venv/lib/python3.14/site-packages (from xgboost) (1.17.1)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip

## Importa Bibliotecas base

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Ler arquivos CSV's

In [5]:
base_cadastros = pd.read_csv("data/base_cadastral.csv", sep=";" )
base_info = pd.read_csv("data/base_info.csv", sep=";" )
base_pagamentos_desenvolvimento = pd.read_csv("data/base_pagamentos_desenvolvimento.csv", sep=";" )
base_pagamentos_teste = pd.read_csv("data/base_pagamentos_teste.csv", sep=";" )

display(base_cadastros.head())
display(base_info.head())
display(base_pagamentos_desenvolvimento.head())
display(base_pagamentos_teste.head())

,ID_CLIENTE,DATA_CADASTRO,DDD,FLAG_PF,SEGMENTO_INDUSTRIAL,DOMINIO_EMAIL,PORTE,CEP_2_DIG
0,1661240395903230676,2013-08-22,99,NaN,Serviços,YAHOO,PEQUENO,65
1,8274986328479596038,2017-01-25,31,NaN,Comércio,YAHOO,MEDIO,77
2,345447888460137901,2000-08-15,75,NaN,Serviços,HOTMAIL,PEQUENO,48
3,1003144834589372198,2017-08-06,49,NaN,Serviços,OUTLOOK,PEQUENO,89
4,324916756972236008,2011-02-14,88,NaN,Serviços,GMAIL,GRANDE,62

            ID_CLIENTE SAFRA_REF  RENDA_MES_ANTERIOR  NO_FUNCIONARIOS
0  1661240395903230676   2018-09             16913.0              NaN
1  8274986328479596038   2018-09            106430.0            141.0
2   345447888460137901   2018-09            707439.0             99.0
3  1003144834589372198   2018-09            239659.0             96.0
4   324916756972236008   2018-09            203123.0            103.0

,ID_CLIENTE,SAFRA_REF,DATA_EMISSAO_DOCUMENTO,DATA_PAGAMENTO,DATA_VENCIMENTO,VALOR_A_PAGAR,TAXA
0,1661240395903230676,2018-08,2018-08-17,2018-09-06,2018-09-06,35516.41,6.99
1,1661240395903230676,2018-08,2018-08-19,2018-09-11,2018-09-10,17758.21,6.99
2,1661240395903230676,2018-08,2018-08-26,2018-09-18,2018-09-17,17431.96,6.99
3,1661240395903230676,2018-08,2018-08-30,2018-10-11,2018-10-05,1341.00,6.99
4,1661240395903230676,2018-08,2018-08-31,2018-09-20,2018-09-20,21309.85,6.99

,ID_CLIENTE,SAFRA_REF,DATA_EMISSAO_DOCUMENTO,DATA_VENCIMENTO,VALOR_A_PAGAR,TAXA
0,5058298901476893676,2021-07,2021-07-14,2021-08-04,11204.75,4.99
1,274692171162531764,2021-07,2021-07-08,2021-08-23,60718.50,5.99
2,274692171162531764,2021-07,2021-07-11,2021-08-25,60718.50,5.99
3,274692171162531764,2021-07,2021-07-16,2021-08-30,62250.00,5.99
4,465309249432033993,2021-07,2021-07-05,2021-07-30,26593.95,6.99

## Imputações BASE INFO

In [158]:
base_info[base_info.isna().any(axis=1)]
data_info = base_info.copy()

In [159]:
base_info[base_info.isna().any(axis=1)]

                ID_CLIENTE SAFRA_REF  RENDA_MES_ANTERIOR  NO_FUNCIONARIOS
0      1661240395903230676   2018-09             16913.0              NaN
13     4395946187332973749   2018-09            251310.0              NaN
22     3248432590399829766   2018-09            217773.0              NaN
23     4095739077267179172   2018-09            292798.0              NaN
25     1078687383992817574   2018-09            412365.0              NaN
...                    ...       ...                 ...              ...
24366  5757271354816214865   2021-12             83165.0              NaN
24368  5753677550753111444   2021-12                 NaN            112.0
24382  3036967290595689189   2021-12                 NaN            151.0
24383  2307201111381758912   2021-12                 NaN             92.0
24390  1667173444642500307   2021-12                 NaN            104.0

[1936 rows x 4 columns]

In [160]:
data_info["NO_FUNCIONARIOS"] = (
    data_info
    .sort_values(["ID_CLIENTE", "SAFRA_REF"])
    .groupby("ID_CLIENTE")["NO_FUNCIONARIOS"]
    .transform(lambda x: x.interpolate(method="linear").ffill().bfill())
    .round()
    .astype("Int16")
)

In [161]:
data_info["RENDA_MES_ANTERIOR"] = (
    data_info
    .sort_values(["ID_CLIENTE", "SAFRA_REF"])
    .groupby("ID_CLIENTE")["RENDA_MES_ANTERIOR"]
    .transform(lambda x: x.interpolate(method="linear").ffill().bfill())
)

## Imputações BASE CADASTROS

In [6]:
base_cadastros[base_cadastros.isna().any(axis=1)]

,ID_CLIENTE,DATA_CADASTRO,DDD,FLAG_PF,SEGMENTO_INDUSTRIAL,DOMINIO_EMAIL,PORTE,CEP_2_DIG
0,1661240395903230676,2013-08-22,99,NaN,Serviços,YAHOO,PEQUENO,65
1,8274986328479596038,2017-01-25,31,NaN,Comércio,YAHOO,MEDIO,77
2,345447888460137901,2000-08-15,75,NaN,Serviços,HOTMAIL,PEQUENO,48
3,1003144834589372198,2017-08-06,49,NaN,Serviços,OUTLOOK,PEQUENO,89
4,324916756972236008,2011-02-14,88,NaN,Serviços,GMAIL,GRANDE,62
...,...,...,...,...,...,...,...,...
1310,3431426889924624821,2020-08-13,92,NaN,Serviços,HOTMAIL,MEDIO,69
1311,5288503299611498087,2020-11-03,NaN,NaN,Comércio,YAHOO,PEQUENO,13
1312,957773253650890560,2021-07-05,NaN,NaN,Comércio,GMAIL,MEDIO,20
1313,6094038865287329652,2021-07-05,NaN,NaN,Serviços,GMAIL,GRANDE,48
1314,1592581784061157609,2002-05-14,(2,NaN,Comércio,NaN,MEDIO,90

In [53]:
data_cadastros = base_cadastros.copy()

data_cadastros["CEP_2_DIG"] = data_cadastros["CEP_2_DIG"].replace('na', np.nan).astype("Int16")
data_cadastros["CEP_2_DIG"] = data_cadastros["CEP_2_DIG"].fillna(data_cadastros["CEP_2_DIG"].mode()[0])

ddd_para_cep2_ranges = {
    11: [(1, 11)],            # SP capital
    12: [(12, 12)],           # Vale do Paraíba
    13: [(13, 13)],           # Campinas
    14: [(14, 14)],           # Barretos
    15: [(15, 15)],           # São José do Rio Preto
    16: [(16, 16)],           # Ribeirão Preto / Araraquara
    17: [(17, 17)],           # Bauru
    18: [(18, 18)],           # Presidente Prudente
    19: [(19, 19)],           # Sorocaba
    21: [(20, 26)],           # RJ capital e região
    22: [(27, 28)],           # RJ interior
    27: [(29, 29)],           # ES
    31: [(30, 33), (35, 35)], # MG - BH e região
    32: [(36, 36)],           # MG - Juiz de Fora
    33: [(39, 39)],           # MG - Governador Valadares
    34: [(34, 34)],           # MG - Uberlândia
    37: [(37, 37)],           # MG - Divinópolis
    38: [(38, 38)],           # MG - Montes Claros
    71: [(40, 41)],           # BA - Salvador
    73: [(47, 47)],           # BA - Ilhéus
    74: [(43, 44)],           # BA - Feira de Santana
    75: [(42, 42)],           # BA - Feira (outra faixa)
    77: [(45, 46)],           # BA - Vitória da Conquista
    79: [(48, 49)],           # SE - Sergipe
    81: [(50, 50), (52, 55)], # PE - Recife
    87: [(51, 51), (56, 56)], # PE - interior
    82: [(57, 57)],           # AL
    83: [(58, 58)],           # PB
    84: [(59, 59)],           # RN
    85: [(60, 61)],           # CE - Fortaleza
    88: [(62, 63)],           # CE - interior
    86: [(64, 64)],           # PI
    98: [(65, 65)],           # MA - São Luís
    99: [(66, 66)],           # MA - interior
    91: [(67, 67)],           # PA - Belém
    93: [(68, 68)],           # PA - Santarém
    96: [(69, 69)],           # AP / RR
    61: [(70, 73)],           # DF / GO - Brasília
    62: [(74, 74), (76, 76)], # GO - Goiânia
    64: [(75, 75)],           # GO - interior
    63: [(77, 77)],           # TO
    65: [(78, 78)],           # MT
    67: [(79, 79)],           # MS
    41: [(80, 83)],           # PR - Curitiba
    42: [(84, 84)],           # PR - Ponta Grossa
    43: [(86, 86)],           # PR - Londrina
    44: [(85, 85), (87, 87)], # PR - Maringá
    48: [(88, 88)],           # SC - Florianópolis
    47: [(89, 89)],           # SC - Blumenau
    51: [(90, 92), (94, 94)], # RS - Porto Alegre
    53: [(96, 96)],           # RS - Pelotas
    54: [(93, 93), (95, 95), (99, 99)], # RS - interior
    55: [(97, 97), (98, 98)], # RS - Santa Maria
}

cep2_para_ddd = {
    cep: ddd
    for ddd, ranges in ddd_para_cep2_ranges.items()
    for start, end in ranges
    for cep in range(start, end + 1)
}

data_cadastros["DDD"] = (
    data_cadastros["DDD"]
    .str.replace(r"\D", "", regex=True)
    .replace("", pd.NA)
    .astype("Int16")
)

data_cadastros.loc[~data_cadastros["DDD"].isin(ddd_para_cep2_ranges.keys()), "DDD"] = pd.NA

mask_nulo = data_cadastros["DDD"].isna()

data_cadastros.loc[mask_nulo, "DDD"] = (
    data_cadastros.loc[mask_nulo, "CEP_2_DIG"]
    .map(cep2_para_ddd, na_action="ignore")
    .astype("Int16")
)

In [54]:
data_cadastros["DOMINIO_EMAIL"] = data_cadastros["DOMINIO_EMAIL"].fillna("UNKNOW")
data_cadastros["DOMINIO_EMAIL"].value_counts()

DOMINIO_EMAIL
YAHOO      392
GMAIL      390
HOTMAIL    323
AOL         74
OUTLOOK     72
BOL         34
UNKNOW      30
Name: count, dtype: int64

In [55]:
data_cadastros["SEGMENTO_INDUSTRIAL"] = data_cadastros["SEGMENTO_INDUSTRIAL"].fillna("UNKNOW")

In [56]:

data_cadastros["FLAG_PF"]=data_cadastros["FLAG_PF"].map({"X":1, np.nan:0})

data_cadastros[data_cadastros.isna().any(axis=1)]

,ID_CLIENTE,DATA_CADASTRO,DDD,FLAG_PF,SEGMENTO_INDUSTRIAL,DOMINIO_EMAIL,PORTE,CEP_2_DIG
21,5301988619224057921,2016-02-24,67,0,Indústria,GMAIL,NaN,79
51,8729164666041467296,2014-03-13,71,0,Serviços,GMAIL,NaN,41
65,5761480994209806499,2015-12-29,31,0,Comércio,YAHOO,NaN,35
112,7031913170099381454,2011-02-14,71,0,Serviços,HOTMAIL,NaN,48
116,8229446069655666941,2011-02-14,18,0,Comércio,HOTMAIL,NaN,16
170,7231408738455755015,2006-07-26,17,0,Serviços,HOTMAIL,NaN,14
312,5988277776808227480,2000-08-15,16,0,Comércio,YAHOO,NaN,15
369,1195244642827484543,2017-09-11,27,0,Comércio,GMAIL,NaN,32
384,5794903898038236832,2000-08-15,21,0,Serviços,GMAIL,NaN,23
402,696014079855281037,2000-08-15,16,0,Serviços,GMAIL,NaN,15
424,2606594191222500726,2010-11-23,85,0,Serviços,GMAIL,NaN,30
445,9086764557051796364,2017-08-17,64,0,Indústria,GMAIL,NaN,75
558,4512887927067894301,2013-11-24,11,0,Comércio,GMAIL,NaN,87
569,4858887739802767402,2004-08-25,21,0,Comércio,YAHOO,NaN,25
589,2808145376905474927,2011-02-14,86,0,Serviços,YAHOO,NaN,64
604,1997130697107291654,2014-06-11,93,0,Comércio,HOTMAIL,NaN,68
623,226405871752897670,2012-08-26,54,0,Serviços,HOTMAIL,NaN,99
629,2208316821038817776,2015-12-13,31,0,Comércio,HOTMAIL,NaN,36
659,2218664010734431754,2018-04-17,83,0,Indústria,YAHOO,NaN,58
700,492136427845699874,2003-10-12,51,0,Serviços,YAHOO,NaN,96
749,6598561842700412652,2018-12-05,12,0,Comércio,YAHOO,NaN,12
787,1152891199251773092,2012-09-23,62,0,Comércio,HOTMAIL,NaN,74
789,186296161813079768,2000-08-15,17,0,Comércio,HOTMAIL,NaN,45
795,6309684992153258710,2018-09-05,33,0,Serviços,GMAIL,NaN,36
819,4631736838128525597,2016-04-19,27,0,Comércio,UNKNOW,NaN,29
866,2493688222671282470,2019-02-18,51,0,Comércio,YAHOO,NaN,80
887,2035700727032031976,2019-07-01,11,0,Comércio,YAHOO,NaN,49
914,1732933177229870014,2019-03-27,11,0,Indústria,OUTLOOK,NaN,69
994,3536704882799524586,2020-04-28,47,0,Indústria,GMAIL,NaN,89
1029,7708030042671632236,2019-03-06,21,0,Comércio,HOTMAIL,NaN,22
1036,1801648099512442340,2019-11-06,31,0,Serviços,HOTMAIL,NaN,32
1050,4137237863152538907,2020-08-06,14,0,Indústria,YAHOO,NaN,14
1109,6724017568171288443,2017-08-06,32,0,Indústria,GMAIL,NaN,36
1114,1207306324957395736,2020-10-18,21,0,Indústria,GMAIL,NaN,25
1129,486388963980110890,2020-09-15,48,0,Comércio,GMAIL,NaN,88
1133,6715993871935527857,2004-05-04,55,0,Comércio,HOTMAIL,NaN,97
1170,2648719990986789645,2015-11-11,65,1,UNKNOW,HOTMAIL,NaN,78
1208,8222831719332844924,2021-04-13,18,0,Serviços,YAHOO,NaN,18
1241,1246864346193559124,2021-05-06,41,0,Indústria,YAHOO,NaN,83
1260,2386535178006664233,2020-08-10,61,1,UNKNOW,HOTMAIL,NaN,71
1302,6518776090651183119,2021-02-04,75,0,UNKNOW,YAHOO,NaN,42

## Imputações BASE DESENVOLVIMENTO

In [153]:
base_pagamentos_desenvolvimento[base_pagamentos_desenvolvimento.isna().any(axis=1)]
data_pagamentos_desenvolvimento = base_pagamentos_desenvolvimento.copy()

In [ ]:
data_pagamentos_desenvolvimento[data_pagamentos_desenvolvimento.isna().any(axis=1)]

##Criar Variaveis de MISSING para ser usado no PAGAMENTO_DESENVOLVIMENTO e no TESTE

In [157]:
data_pagamentos_desenvolvimento["VALOR_MISSING"] = data_pagamentos_desenvolvimento["VALOR_A_PAGAR"].isna().astype(int)

med_cs = data_pagamentos_desenvolvimento.groupby(["ID_CLIENTE", "SAFRA_REF"])["VALOR_A_PAGAR"].median()
med_c = data_pagamentos_desenvolvimento.groupby("ID_CLIENTE")["VALOR_A_PAGAR"].median()
med_global = data_pagamentos_desenvolvimento["VALOR_A_PAGAR"].median()


med_cs_df = med_cs.reset_index().rename(columns={"VALOR_A_PAGAR": "med_cs"})
med_c_df = med_c.reset_index().rename(columns={"VALOR_A_PAGAR": "med_c"})

# # merge
data_pagamentos_desenvolvimento = data_pagamentos_desenvolvimento.merge(med_cs_df, on=["ID_CLIENTE", "SAFRA_REF"], how="left")
data_pagamentos_desenvolvimento = data_pagamentos_desenvolvimento.merge(med_c_df, on="ID_CLIENTE", how="left")

# # imputação hierárquica
data_pagamentos_desenvolvimento["VALOR_A_PAGAR"] = data_pagamentos_desenvolvimento["VALOR_A_PAGAR"].fillna(data_pagamentos_desenvolvimento["med_cs"])
data_pagamentos_desenvolvimento["VALOR_A_PAGAR"] = data_pagamentos_desenvolvimento["VALOR_A_PAGAR"].fillna(data_pagamentos_desenvolvimento["med_c"])
data_pagamentos_desenvolvimento["VALOR_A_PAGAR"] = data_pagamentos_desenvolvimento["VALOR_A_PAGAR"].fillna(med_global)

# # opcional: limpar colunas auxiliares
data_pagamentos_desenvolvimento.drop(columns=["med_cs", "med_c"], inplace=True)

#Criar variavel de Inadinplencia

In [ ]:

data_pagamentos_desenvolvimento["DATA_EMISSAO_DOCUMENTO"] = pd.to_datetime(data_pagamentos_desenvolvimento["DATA_EMISSAO_DOCUMENTO"], errors="coerce")
data_pagamentos_desenvolvimento["DATA_PAGAMENTO"] = pd.to_datetime(data_pagamentos_desenvolvimento["DATA_PAGAMENTO"], errors="coerce")
data_pagamentos_desenvolvimento["DATA_VENCIMENTO"] = pd.to_datetime(data_pagamentos_desenvolvimento["DATA_VENCIMENTO"], errors="coerce")

data_pagamentos_desenvolvimento["INADIMPLENTE"] = (data_pagamentos_desenvolvimento["DATA_PAGAMENTO"] >= data_pagamentos_desenvolvimento["DATA_VENCIMENTO"]+pd.Timedelta(days=5)).astype(int)
data_pagamentos_desenvolvimento["INADIMPLENTE"].value_counts()

ID_CLIENTE           SAFRA_REF
8784237149961904     2018-08      94062.800
                     2018-09      57513.755
                     2018-10      52174.450
                     2018-11      85615.000
                     2018-12      70478.800
                                    ...
9206030810342980458  2021-02      92561.650
                     2021-03      38414.290
                     2021-04      82150.200
                     2021-05      67491.400
                     2021-06      50454.200
Name: VALOR_A_PAGAR, Length: 21121, dtype: float64

In [162]:
data_pagamentos_desenvolvimento

,ID_CLIENTE,SAFRA_REF,DATA_EMISSAO_DOCUMENTO,DATA_PAGAMENTO,DATA_VENCIMENTO,VALOR_A_PAGAR,TAXA,INADIMPLENTE,VALOR_MISSING
0,1661240395903230676,2018-08,2018-08-17,2018-09-06,2018-09-06,35516.41,6.99,0,0
1,1661240395903230676,2018-08,2018-08-19,2018-09-11,2018-09-10,17758.21,6.99,0,0
2,1661240395903230676,2018-08,2018-08-26,2018-09-18,2018-09-17,17431.96,6.99,0,0
3,1661240395903230676,2018-08,2018-08-30,2018-10-11,2018-10-05,1341.00,6.99,1,0
4,1661240395903230676,2018-08,2018-08-31,2018-09-20,2018-09-20,21309.85,6.99,0,0
...,...,...,...,...,...,...,...,...,...
77409,2951563549197799278,2021-06,2021-06-30,2021-07-16,2021-07-16,89980.00,5.99,0,0
77410,5220206408301580591,2021-06,2021-06-30,2021-08-16,2021-08-16,42239.00,5.99,0,0
77411,5860276371789140450,2021-06,2021-06-30,2021-07-16,2021-07-16,20921.50,5.99,0,0
77412,2814790209436551216,2021-06,2021-06-30,2021-07-16,2021-07-16,90231.05,6.99,0,0
77413,8343941262792249232,2021-06,2021-06-30,2021-08-16,2021-08-16,20736.51,4.99,0,0